### ISSUE TITLE
Twig_Error_Runtime exception when showing date

### ISSUE THREAD

**Issue by dirkaholic** [michelsalib/BCCResqueBundle#24]
Seems like the used date format is sometimes not parsable by DateTime, I regularly get 500 errors with that message in the logs:

Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("DateTime::__construct(): Failed to parse time string (Mi Jan 09 11:35:21 CET 2013) at position 0 (M): The timezone could not be found in the database") in "BCCResqueBundle:Default:index.html.twig" at line 101

When trying: 

php -r '$date = new DateTime("Mi Jan 09 11:35:21 CET 2013");'

you get the same error.

**Comment by clintonhsg** [comment]
Hi,

I am having the same problem on a dedicated server where I have no control over (PHP settings). I am currently using v1.34.4 because our host service does not support PHP 7 but PHP 5.6.

Please can you advise what version you guys where refering too wher michelsalib said 

> Can you try again with last version ? It should be fixed now/

 dirkaholic do you know the version you used to correct the problem?

Any help is appreciated

### edit
Hi guys,

I apologise my problem was to do with an invalid value been passed to the date filter. Please ignore my message.
